import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generate & download a branded Deja Brew PDF report.
 * rows: array of data rows
 * columns: [{ key, label, format? }]
 * opts: { filename, title, subtitle, summaryLines? }
 */
export function downloadPdf(rows, columns, opts = {}) {
  const { filename = "dejabrew.pdf", title = "Report", subtitle = "", summaryLines = [] } = opts;
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  // Header band (coffee brown)
  doc.setFillColor(139, 90, 43); // #8B5A2B
  doc.rect(0, 0, pageW, 68, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Deja Brew", 40, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("ERP Report", 40, 46);
  // Right-aligned title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, pageW - 40, 30, { align: "right" });
  if (subtitle) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, pageW - 40, 46, { align: "right" });
  }

  // Generated timestamp
  doc.setTextColor(140, 125, 113);
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString("en-IN")}`, 40, 88);

  // Summary card
  let cursorY = 108;
  if (summaryLines.length > 0) {
    doc.setFillColor(246, 243, 236); // #F6F3EC
    doc.roundedRect(40, cursorY - 12, pageW - 80, 18 * summaryLines.length + 8, 6, 6, "F");
    doc.setTextColor(44, 36, 27);
    doc.setFontSize(9);
    summaryLines.forEach((line, i) => {
      doc.setFont("helvetica", "bold");
      doc.text(line.label, 52, cursorY + i * 18);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(139, 90, 43);
      doc.text(String(line.value), 200, cursorY + i * 18);
      doc.setTextColor(44, 36, 27);
    });
    cursorY += summaryLines.length * 18 + 14;
  }

  // Table
  autoTable(doc, {
    startY: cursorY,
    head: [columns.map((c) => c.label)],
    body: rows.map((r) =>
      columns.map((c) => {
        const v = c.format ? c.format(r[c.key], r) : r[c.key];
        return v === null || v === undefined ? "" : String(v);
      })
    ),
    styles: { fontSize: 8.5, cellPadding: 5, textColor: [44, 36, 27] },
    headStyles: { fillColor: [139, 90, 43], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [246, 243, 236] },
    margin: { left: 40, right: 40 },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(140, 125, 113);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.text(`Page ${i} / ${pageCount}`, pageW - 40, h - 20, { align: "right" });
    doc.text("Deja Brew · Generated by ERP", 40, h - 20);
  }

  doc.save(filename);
}
